config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/about' => 'pages#about'
  get '/definitions' => 'pages#definitions'
  get '/presentation' => 'pages#presentation'

  resources :fixtures do
    collection {post :import}
    resources :cargoes, only: [:create, :update]
    resources :events, only: [:index, :new, :create] do
      collection { post :import, :run_chronos }
      end
    end
  resources :clause_groups
  resources :clauses
end

app/models/fixture.rb
class Fixture < ApplicationRecord
  has_many :cargoes, class_name: "FixtureCargo", dependent: :destroy
  belongs_to :clause_group, optional: true
  # has_many :fixture_cargos, inverse_of: :fixture

  # validates :reference_no, presence: true, numericality: { greater_than: 0 }
  validates :vessel_name, presence: true
  validates :charterer, presence: true
  validates :voyage_number, presence: true, numericality: { greater_than: 0 }
  # validates :demurrage_rate, presence: true, numericality: { greater_than: 0, only_integer: true }
  # validates :allowed_laytime, presence: true, numericality: { greater_than: 0 }
  # validates :clause_group_id, presence: true, numericality: { greater_than: 0 }

  # Required for cocoon nested forms gem
  # accepts_nested_attributes_for :fixture_cargos, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :cargoes, reject_if: :all_blank, allow_destroy: true
end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
  before_action :set_fixture, only: %i[show edit update]

  def import
    @fixture = ImportFixtureJob.perform_now(params[:file])
    redirect_to fixture_path(@fixture), notice: "Fixture data imported"
  end

  def index
    @fixtures = Fixture.all.sort_by{ |fixture| fixture.days_until_completion }
    @fixture = Fixture.new
  end

  def show
    @fixture_cargo = FixtureCargo.new
  end

  def new
  end

  def create
    @fixture = Fixture.new(fixture_params)
    @fixture.save!

    redirect_to fixture_path(@fixture)
  end

  def edit
  end

  def update
    @fixture.update(fixture_params)

    redirect_to fixture_path(@fixture)
  end

  private

  def set_fixture
    @fixture = Fixture.find(params[:id])
  end

  def fixture_params
    params.fetch(:fixture, {}).permit(:charterer, :clause_group_id, :vessel_name, :voyage_number, :demurrage_rate, :allowed_laytime,
                                      # Used for cocoon nesting forms to pass all FixtureCargo attributes and destroy method in params
                                      cargoes_attributes: FixtureCargo.attribute_names.map(&:to_sym).push(:_destroy))
  end
end

app/views/fixtures/_cargo_discharge_row.html.erb
<tr>
  <!-- Discharge Port -->
  <td class="align-middle"><%= cargo.disch_port unless suppressed_fields[:disch_port] %></td>
  <!-- Discharge Terminal -->
  <td class="align-middle"><%= cargo.disch_terminal unless suppressed_fields[:disch_terminal] %></td>
  <!-- Discharge Berth -->
  <td class="align-middle"><%= cargo.disch_berth unless suppressed_fields[:disch_berth] %></td>
  <!-- Obl -->
  <td class="align-middle"><%= cargo.obl %></td>
  <!-- Cargo Name -->
  <td class="align-middle"><%= cargo.name %></td>
  <!-- Qty - Mts -->
  <td class="align-middle"><%= cargo.quantity_mts %></td>
</tr>

app/views/fixtures/_cargo_fields.html.erb
<tr>
  <td>
    <%= f.input :"#{prefix}_port",
                  input_html: {readonly: true, class: "form-control-sm edit-input"},
                  label: false,
                  required: true %>
  </td>
  <td>
    <%= f.input :"#{prefix}_terminal",
                  input_html: {readonly: true, class: "form-control-sm edit-input"},
                  label: false,
                  required: true %>
  </td>
  <td>
    <%= f.input :"#{prefix}_berth",
                  input_html: {readonly: true, class: "form-control-sm edit-input"},
                  label: false,
                  required: true %>
  </td>
  <td>
    <%= f.input :obl,
                  input_html: {readonly: true, class: "form-control-sm edit-input"},
                  label: false,
                  required: true, disabled: prefix.eql?('disch') %>
  </td>
  <td>
    <%= f.input :name,
                input_html: {readonly: true, class: "form-control-sm edit-input"},
                label: false,
                required: true, disabled: prefix.eql?('disch') %>
  </td>
  <td>
    <%= f.input :quantity_mts,
                input_html: {readonly: true, class: "form-control-sm edit-input"},
                label: false,
                required: true, disabled: prefix.eql?('disch') %>
  </td>
</tr>

app/views/fixtures/_cargo_loading_row.html.erb
<tr>
  <!-- Loading Port -->
  <td class="align-middle"><%= cargo.load_port unless suppressed_fields[:load_port] %></td>
  <!-- Loading Terminal -->
  <td class="align-middle"><%= cargo.load_terminal unless suppressed_fields[:load_terminal] %></td>
  <!-- Loading Berth -->
  <td class="align-middle"><%= cargo.load_berth unless suppressed_fields[:load_berth] %></td>
  <!-- Obl -->
  <td class="align-middle"><%= cargo.obl %></td>
  <!-- Cargo Name -->
  <td class="align-middle"><%= cargo.name %></td>
  <!-- Qty - Mts -->
  <td class="align-middle"><%= cargo.quantity_mts %></td>
</tr>

app/views/fixtures/_cargo_show.html.erb
<h4 class="mt-4 mb-3">Loading</h4>

<table class="table">
  <thead>
    <tr>
      <th style="width: 20%">Port</th>
      <th style="width: 15%">Terminal</th>
      <th>Berth</th>
      <th>Obl</th>
      <th style="width: 25%">Name</th>
      <th>Qty - Mts</th>
    </tr>
  </thead>
  <tbody>
    <% last_port = nil %>
    <% last_terminal = nil %>
    <% last_berth = nil %>
    <% @fixture.cargoes.each do |cargo| %>
      <% suppressed_fields = { load_port: cargo.load_port == last_port,
                               load_terminal: cargo.load_terminal == last_terminal,
                               load_berth: cargo.load_berth == last_berth } %>
      <% last_port = cargo.load_port %>
      <% last_terminal = cargo.load_terminal %>
      <% last_berth = cargo.load_berth %>
      <%= render 'cargo_loading_row', cargo: cargo, suppressed_fields: suppressed_fields %>
    <% end %>
  </tbody>
</table>

<h4 class="mt-4 mb-3">Discharge</h2>

<table class="table">
  <thead>
    <tr>
      <th style="width: 20%">Port</th>
      <th style="width: 15%">Terminal</th>
      <th>Berth</th>
      <th>Obl</th>
      <th style="width: 25%">Name</th>
      <th>Qty - Mts</th>
    </tr>
  </thead>
  <tbody>
    <% last_port = nil %>
    <% last_terminal = nil %>
    <% last_berth = nil %>
    <% @fixture.cargoes.each do |cargo| %>
      <% suppressed_fields = { disch_port: cargo.disch_port == last_port,
                               disch_terminal: cargo.disch_terminal == last_terminal,
                               disch_berth: cargo.disch_berth == last_berth } %>
      <% last_port = cargo.disch_port %>
      <% last_terminal = cargo.disch_terminal %>
      <% last_berth = cargo.disch_berth %>
      <%= render 'cargo_discharge_row', cargo: cargo, suppressed_fields: suppressed_fields %>
    <% end %>
  </tbody>
</table>

app/views/fixtures/_clause_show.html.erb
<div id="clauses-container">
  <div class="clause-group-select">
    <%= simple_form_for @fixture do |f| %>
      <%= f.input :clause_group_id, collection: ClauseGroup.all, label: "Select Contract Clauses" %>
    <% end %>
  </div>

  <div class="table-responsive">
    <table class="table-striped table borderless" id="load_clause_group">
      <thead>
        <tr>
          <th>Parent</th>
          <th>Title</th>
          <th>Wording</th>
          <th class="adjust-width">Clause ID</th>
          <th>+</th>
        </tr>
      </thead>

      <tbody>
        <% @fixture.clause_group&.clauses&.each do |clause| %>
          <tr>
            <td><%= "#{clause.cp_form.upcase}" + " " + "#{clause.parent_relation}" %></td>
            <td>
              <div class=row">
                <div class="col">
                  <%= "#{clause.title.titleize}" %>
                </div>
                <div class="col">
                  <%= "#{clause.paragraph}" %>
                </div>
              </div>
            </td>
            <td><%= clause.wording %></td>
            <td><%= clause.id %></td>
            <td>
               <button id="btnGroupDrop1" type="button" class="btn btn-curious-blue dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</button>

               <div class="dropdown-menu" role="menu">
                <%= link_to "Amend details", edit_clause_path(clause), class: "dropdown-item" %>
                <%= link_to 'Delete',
                clause_path(clause),
                method: :delete,
                data: { confirm: 'Are you sure you want to delete this item?' }, class: "dropdown-item" %>
                <%= link_to "Request bloc change", new_clause_path, class: "dropdown-item" %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/fixtures/_fixture.html.erb
<tr>
  <!-- Vessel -->
  <td class="align-middle"><%= @fixture.vessel_name %></td>
  <!-- Voyage No. -->
  <td class="align-middle"><%= @fixture.voyage_number %></td>
  <!-- Charterer -->
  <td class="align-middle"><%= @fixture.charterer %></td>
  <!-- Demurrage Est. -->
  <td class="align-middle"><%= @fixture.total_demurrage %></td>
  <!-- Fixture (Ref. No) -->
  <td class="align-middle"><%= @fixture.reference_no %></td>
  <!-- Required -->
  <td class="align-middle"><%= @fixture.calculation_status %></td>
  <!-- Documents -->
  <td class="align-middle">
    <div class="dropdown">
      <button class="btn btn-niagara btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span id="selected">Documents</span>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="#">Incomplete</a>
        <a class="dropdown-item" href="#">Complete</a>
      </div>
    </div>
  </td>
  <!-- Voyage Status -->
  <td class="align-middle">..</td>
  <!-- + -->
  <td class="align-middle">
    <%= link_to "Demurrage record", fixture_events_path(@fixture), class: "btn btn-curious-blue" %>
  </td>
</tr>

app/views/fixtures/_fixture_fields.html.erb
<% clause_group = @fixture.clause_group %>
<% join = ClauseGroupJoin.where(clause_group: clause_group).first %>

<% total_cargo = 0 %>
<% FixtureCargo.where(fixture: @fixture).each {|cargo| total_cargo += cargo.quantity_mts } %>

<div class="row">
  <div class='col-md-3'>
    <%= f.input :reference_no,
                input_html: {readonly: true, class: "form-control-sm edit-input"},
                label: "Reference No.",
                placeholder: @fixture.reference_no,
                required: true %>
  </div>
  <div class="col-md-3">
    <%= f.input :voyage_number,
                input_html: {readonly: true, class: "form-control-sm edit-input"},
                label: "Voyage No.",
                placeholder: @fixture.voyage_number.to_s,
                required: true %>
  </div>
  <div class="col-md-4">
    <%= f.input :clause_group, as: :fake,
                input_html: {readonly: true, class: "form-control-sm edit-input autofill"},
                label: "CP Form",
                placeholder: join.nil? ? "" : join.clause.cp_form,
                required: true %>
  </div>
</div>

<div class="row">
  <div class='col-md-3'>
    <%= f.input :vessel_name,
                input_html: {readonly: true, class: "form-control-sm edit-input"},
                label: "Vessel Name",
                placeholder: @fixture.vessel_name,
                required: true %>
  </div>
  <div class="col-md-3">
    <%= f.input :charterer,
                input_html: {readonly: true, class: "form-control-sm edit-input"},
                label: "Charterer",
                placeholder: @fixture.charterer,
                required: true %>
  </div>

  <div class="col-md-4">
    <%= f.input :contract_type, as: :fake,
                input_html: {readonly: true, class: "form-control-sm edit-input autofill"},
                label: "Contract Type",
                placeholder: "SPOT",
                required: true %>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <%= f.input :vessel_dwt, as: :fake,
                input_html: {readonly: true, class: "form-control-sm edit-input"},
                label: "Vessel Capacity",
                placeholder: "35 000 mts",
                required: false %>
  </div>

  <div class="col-md-3">
    <%= f.input :demurrage_rate,
                input_html: {readonly: true, class: "form-control-sm edit-input"},
                label: "Demurrage Rate",
                required: false %>
  </div>
  <div class="col-md-4">
    <%= f.input :contract_terms, as: :fake,
                input_html: {readonly: true, class: "form-control-sm edit-input autofill"},
                label: "Contract Terms",
                placeholder: clause_group.nil? ? "" : clause_group.name,
                required: false %>
  </div>
</div>

<div class="row">
  <div class="col-md-3">
    <%= f.input :total_cargo_qty, as: :fake,
                input_html: {readonly: true, class: "form-control-sm edit-input autofill"},
                label: "Total Cargo",
                placeholder: total_cargo.to_s + " mts",
                required: false %>
  </div>
  <div class="col-md-3">
    <%= f.input :allowed_laytime,
                input_html: {readonly: true, class: "form-control-sm edit-input"},
                label: "Allowed Laytime",
                placeholder: @fixture.allowed_laytime.nil? ? "" : @fixture.allowed_laytime.to_s + " hours total",
                required: false %>
  </div>
  <div class="col-md-4">
    <%= f.input :reversable, as: :fake,
                input_html: {readonly: true, class: "form-control-sm edit-input"},
                label: "Reversible",
                placeholder: "yes",
                required: false %>
  </div>
</div>

app/views/fixtures/_fixture_index_row.html.erb
<tr data-link="<%= fixture_path(fixture) %>">
  <!-- Vessel -->
  <td class="align-middle"><%= fixture.vessel_name %></td>
  <!-- Voyage No. -->
  <td class="align-middle"><%= fixture.voyage_number %></td>
  <!-- Charterer -->
  <td class="align-middle"><%= fixture.charterer %></td>
  <!-- Demurrage Est. -->
  <td class="align-middle"><%= number_to_currency(fixture.total_demurrage, precision: 0, delimiter: ' ', unit: "USD", format: "%n %u" ) %></td>
  <!-- Fixture (Ref. No) -->
  <td class="align-middle"><%= fixture.reference_no %></td>
  <!-- Required -->
  <td class="align-middle"><%= fixture.required_action %></td>
  <!-- Voyage Status -->
  <td class="align-middle"><%= fixture.days_until_completion %></td>
  <!-- voy status -->
  <td class="align-middle"><%= fixture.voyage_status %></td>
  <!-- + -->
  <td class="align-middle">
    <%= link_to "Demurrage Report", fixture_events_path(fixture), class: "btn special-btn-outline" %>
  </td>
</tr>

app/views/fixtures/_fixture_new_modal.html.erb
<!-- Button trigger modal -->
<div class="modal-svg-wrapper mt-5" id="modal-hover-btn" type="button" data-toggle="modal" data-target="#exampleModalCenter">
  <svg height="60" width="320" xmlns="http://www.w3.org/2000/svg">
    <rect class="shape" height="60" width="320" />
    <div class="modal-hover-text">Add Fixture</div>
  </svg>
</div>

<div class="modal modal-wide fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centere" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Add a New Fixture</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
          <div class="container-fluid">

            <h3 class="mt-3 mb-3 d-flex justify-content-center header-spacing">Import Fixture Spreadsheet</h3>

            <div class="d-flex justify-content-center">
              <div class="import-file modal-outset">
                  <%= form_tag import_fixtures_path, multipart: true do %>
                    <%= file_field_tag :file %>
                    <%= submit_tag "Import Fixture", class: "btn btn-curious-blue" %>
                  <% end %>
              </div>
            </div>

            <h5 class="mt-3 mb-3 d-flex justify-content-center">--OR--</h5>

            <div class="mt-3 mb-3 d-flex justify-content-center">
              <button type="button" class="btn btn-lg special-btn-outline" id="modalManualBtn">
                Enter Fixture Manually
              </button>
            </div>

            <div class="container modal-hidden" style="display: none">
              <div class="d-flex justify-content-around">
                <div class='col-md-3'>
                  <%= simple_form_for @fixture, url: fixtures_path, method: :post do |f| %>
                  <%= f.input :reference_no,
                              input_html: {class: "form-control-sm edit-input"},
                              label: "Reference No.",
                              required: true %>
                </div>
                <div class="col-md-3">
                  <%= f.input :voyage_number,
                              input_html: {class: "form-control-sm edit-input"},
                              label: "Voyage No.",
                              label_html: {class: ""},
                              required: true %>
                </div>
                <div class="col-md-3">
                  <%= f.input :clause_group, as: :fake,
                              input_html: {class: "form-control-sm edit-input"},
                              label: "CP Form*",
                              required: true %>
                </div>
              </div>

              <div class="d-flex justify-content-around">
                <div class='col-md-3'>
                  <%= f.input :vessel_name,
                              input_html: {class: "form-control-sm edit-input"},
                              label: "Vessel Name",
                              required: true %>
                </div>
                <div class="col-md-3">
                  <%= f.input :charterer,
                              input_html: {class: "form-control-sm edit-input"},
                              label: "Charterer",
                              required: true %>
                </div>

                <div class="col-md-3">
                  <%= f.input :contract_type, as: :fake,
                              input_html: {class: "form-control-sm edit-input"},
                              label: "Contract Type*",
                              label_html: {class: ""},
                              required: true %>
                </div>
              </div>

              <div class="d-flex justify-content-around">
                <div class="col-md-3">
                  <%= f.input :vessel_dwt, as: :fake,
                              input_html: {class: "form-control-sm edit-input"},
                              label: "Vessel DWT*",
                              label_html: {class: ""},
                              required: false %>
                </div>

                <div class="col-md-3">
                  <%= f.input :demurrage_rate,
                              input_html: {class: "form-control-sm edit-input"},
                              label: "Demurrage Rate",
                              label_html: {class: ""},
                              required: false %>
                </div>
                <div class="col-md-3">
                  <%= f.input :contract_terms, as: :fake,
                              input_html: {class: "form-control-sm edit-input"},
                              label: "Contract Terms*",
                              label_html: {class: ""},
                              required: false %>
                </div>
              </div>

              <div class="d-flex justify-content-around">
                <div class="col-md-3">
                  <%= f.input :total_cargo_qty, as: :fake,
                              input_html: {class: "form-control-sm edit-input"},
                              label: "Total Cargo Qty*",
                              required: false %>
                </div>
                <div class="col-md-3">
                  <%= f.input :allowed_laytime,
                              input_html: {class: "form-control-sm edit-input"},
                              label: "Allowed Laytime",
                              required: false %>
                </div>
                <div class="col-md-3">
                  <%= f.input :reversible, as: :fake,
                              input_html: {class: "form-control-sm edit-input"},
                              label: "Reversible",
                              required: false %>
                </div>
              </div>
            </div>
          </div>
      </div>
      <div class="modal-footer">
          <%= link_to "Cancel", fixtures_path, class: "btn btn-secondary" %>
          <!-- <%= f.button :button, "Cancel", class: "btn btn-secondary" %> -->
          <%= f.button :submit, "Create Fixture", class: "btn btn-curious-blue modal-hidden", style: "display: none" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/fixtures/_fixture_row.html.erb
<tr>
  <!-- + -->
  <td class="align-middle">
    <%= link_to "View fixture", fixture_path(fixture), class: "btn btn-curious-blue btn-sm" %>
  </td>
  <!-- Vessel -->
  <td class="align-middle"><%= fixture.vessel_name %></td>
  <!-- Voyage No. -->
  <td class="align-middle"><%= fixture.voyage_number %></td>
  <!-- Charterer -->
  <td class="align-middle"><%= fixture.charterer %></td>
  <!-- Demurrage Est. -->
  <td class="align-middle"><%= fixture.total_demurrage %></td>
  <!-- Fixture (Ref. No) -->
  <td class="align-middle"><%= fixture.reference_no %></td>
  <!-- Required -->
  <td class="align-middle"><%= fixture.calculation_status %></td>
  <!-- Documents -->
  <td class="align-middle">
    <div class="dropdown">
      <button class="btn btn-niagara btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span id="selected">Documents</span>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <a class="dropdown-item" href="#">Incomplete</a>
        <a class="dropdown-item" href="#">Complete</a>
      </div>
    </div>
  </td>
  <!-- Voyage Status -->
  <td class="align-middle">..</td>
  <!-- + -->
  <td class="align-middle">
    <%= link_to "Demurrage record", fixture_events_path(fixture), class: "btn btn-curious-blue" %>
  </td>
</tr>

app/views/fixtures/edit.html.erb
<div class="container-fluid px-6">
  <!-- Form for view Fixture -->
  <h2 class="mt-5 mb-3">Fixture Details</h2>

  <%= simple_form_for @fixture, html: { class: 'super-edit-power' } do |ff| %>
    <div class="btn btn-default toggle mt-3 mb-3" id="edit-button">
      <div class="slide">
        <i class="fas fa-circle"></i>
      </div>
    </div>
    <%= render 'fixture_fields', f: ff %>


    <hr />

  <!-- Add cargo button
  TO BE ADDED AS A MODEL OR A COCOON EVENT LATER
  For details on how to do the cocoon stuff, look at Steven's code in the show_old page below.
  -->

    <h2 class="mt-3 mb-3">Cargo</h2>
      <div class="big-edit" style="display: block"><%= render "cargo_show" %></div>
      <div class="big-edit" style="display: none"><%= render "cargo_edit", ff: ff %></div>
    <hr />
    <h2 class="mt-3 mb-3"><a name="clauses">Clauses</a></h2>
      <%= render 'clause_show' %>
  <% end %>
</div>

app/views/fixtures/index.html.erb
<!-- Begin page content -->
<div class="container-fluid px-6">
  <%= render "fixture_new_modal" %>
  <div class="card">
    <h2>Fixtures</h2>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Vessel</th>
            <th>Voy</th>
            <th>Charterer</th>
            <th>Demurrage</th>
            <th>Fixture</th>
            <th>Required</th>
            <th>ETC</th>
            <th>Voyage Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody id="fixtures-table">

          <% @fixtures.each do |fixture| %>
            <%= render "fixture_index_row", fixture: fixture %>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/fixtures/show.html.erb
<div class="container-fluid px-6">
  <!-- Form for view Fixture -->
  <%= simple_form_for @fixture, html: { class: 'super-edit-power' } do |ff| %>

    <div class="card">
      <div class="d-flex justify-content-between">
        <h2 class="mb-2">Fixture Details</h2>
        <div class="btn btn-default toggle" id="edit-button">
          <div class="slide">
            <i class="fas fa-circle"></i>
          </div>
        </div>
      </div>
      <div class="fixture-details">
        <div class="fixture-details-container">
          <div class="big-edit" style="display: block">
            <%= render "shared/fixture_details", fixture: @fixture %>
          </div>
          <div class="big-edit" style="display: none">
            <%= render "fixture_fields", f: ff %>
          </div>
        </div>
          <div class="fixture-buttons-container">
            <%= link_to "Demurrage Report", fixture_events_path(@fixture), class: "btn btn-lg special-btn-outline", id: "demurrage-btn" %>
          </div>
      </div>
    </div>

  <div class="card">
    <div class="d-flex justify-content-between">
      <h2 class="mb-2">Cargo Details</h2>
      <div class="btn btn-default toggle" id="edit-button">
        <div class="slide">
          <i class="fas fa-circle"></i>
        </div>
      </div>
    </div>
      <div class="big-edit" style="display: block">
        <%= render "cargo_show" %>
      </div>
      <div class="big-edit" style="display: none">
        <%= render "cargo_edit", ff: ff %>
      </div>
  </div>

  <div class="card">
    <div class="d-flex justify-content-between">
      <h2 class="mb-3"><a name="clauses">Contract Details</a></h2>
      <div class="btn btn-default toggle mt-3 mb-3" id="edit-button">
        <div class="slide">
          <i class="fas fa-circle"></i>
        </div>
      </div>
    </div>
    <%= render 'clause_show' %>
  </div>
  <% end %>
</div>

<!-- Add cargo button

TO BE ADDED AS A MODAL OR A COCOON EVENT LATER
For details on how to do the cocoon stuff, look at Steven's code in the show_old page below.

-->