config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/about' => 'pages#about'
  get '/definitions' => 'pages#definitions'
  get '/presentation' => 'pages#presentation'

  resources :fixtures do
    collection {post :import}
    resources :cargoes, only: [:create, :update]
    resources :events, only: [:index, :new, :create] do
      collection { post :import, :run_chronos }
      end
    end
  resources :clause_groups
  resources :clauses
end

app/views/shared/_blob_button.html.erb
<button class="blob-btn">
  How It Works
  <span class="blob-btn__inner">
    <span class="blob-btn__blobs">
      <span class="blob-btn__blob"></span>
      <span class="blob-btn__blob"></span>
      <span class="blob-btn__blob"></span>
      <span class="blob-btn__blob"></span>
    </span>
  </span>
</button>

app/views/shared/_clauses_table.html.erb
  <div class="table-responsive">
    <table class="table-striped table borderless">
      <thead>
        <tr>
          <th>Parent</th>
          <th>Title</th>
          <th>Wording</th>
          <th class="adjust-width">Clause ID</th>
          <th>+</th>
        </tr>
      </thead>

      <tbody>
        <% @clauses.clauses.each do |clause| %>
          <tr>
            <td><%= "#{clause.cp_form.upcase}" + " " + "#{clause.parent_relation}" %></td>
            <td>
              <div class=row">
                <div class="col">
                  <%= "#{clause.title.titleize}" %>
                </div>
                <div class="col">
                  <%= "#{clause.paragraph}" %>
                </div>
            </div>
          </td>
          <td><%= clause.wording %></td>
          <td><%= clause.id %></td>
          <td>
           <button id="btnGroupDrop1" type="button" class="btn btn-curious-blue dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</button>
           <div class="dropdown-menu" role="menu">
            <%= link_to "Amend details", edit_clause_path(clause), class: "dropdown-item" %>
            <%= link_to 'Delete',
            clause_path(clause),
            method: :delete,
            data: { confirm: 'Are you sure you want to delete this item?' }, class: "dropdown-item" %>
            <%= link_to "Request bloc change", new_clause_path, class: "dropdown-item" %>
          </div>
        </td>
      </tr>
      <% end %>
     </tbody>
    </table>
  </div>

app/views/shared/_favicon.html.erb
<%= favicon_link_tag asset_path("favicon/apple-icon-57x57.png"), rel: "apple-touch-icon", sizes: "57x57" %>
<%= favicon_link_tag asset_path("favicon/apple-icon-60x60.png"), rel: "apple-touch-icon", sizes: "60x60" %>
<%= favicon_link_tag asset_path("favicon/apple-icon-72x72.png"), rel: "apple-touch-icon", sizes: "72x72" %>
<%= favicon_link_tag asset_path("favicon/apple-icon-76x76.png"), rel: "apple-touch-icon", sizes: "76x76" %>
<%= favicon_link_tag asset_path("favicon/apple-icon-114x114.png"), rel: "apple-touch-icon", sizes: "114x114" %>
<%= favicon_link_tag asset_path("favicon/apple-icon-120x120.png"), rel: "apple-touch-icon", sizes: "120x120" %>
<%= favicon_link_tag asset_path("favicon/apple-icon-144x144.png"), rel: "apple-touch-icon", sizes: "144x144" %>
<%= favicon_link_tag asset_path("favicon/apple-icon-152x152.png"), rel: "apple-touch-icon", sizes: "152x152" %>
<%= favicon_link_tag asset_path("favicon/apple-icon-180x180.png"), rel: "apple-touch-icon", sizes: "180x180" %>
<%= favicon_link_tag asset_path("favicon/android-icon-192x192.png"), rel: "icon", type: "image/png", sizes: "192x192" %>
<%= favicon_link_tag asset_path("favicon/favicon-32x32.png"), rel: "icon", type: "image/png", sizes: "32x32" %>
<%= favicon_link_tag asset_path("favicon/favicon-96x96.png"), rel: "icon", type: "image/png", sizes: "96x96" %>
<%= favicon_link_tag asset_path("favicon/favicon-16x16.png"), rel: "icon", type: "image/png", sizes: "16x16" %>
<link href: "favicon/manifest.json" rel: "manifest" %>
<meta name: "favicon/msapplication-TileColor" content: "#ffffff" %>
<meta name: "favicon/msapplication-TileImage" content: "/ms-icon-144x144.png" %>
<meta name: "favicon/theme-color" content: "#ffffff" %>

app/views/shared/_fixture_details.html.erb
<% clause_group = fixture.clause_group %>
<% join = ClauseGroupJoin.where(clause_group: clause_group).first %>

<% total_cargo = 0 %>
<% FixtureCargo.where(fixture: fixture).each {|cargo| total_cargo += cargo.quantity_mts } %>

<div class="details-container">
  <div class="row">
    <div class='col-md-3'>
      <div class="details-group">
        <p class="details-label">Reference No.</p>
        <p class="details-value"><%= fixture.reference_no %></p>
      </div>
    </div>
    <div class="col-md-3">
      <div class="details-group">
        <p class="details-label">Voyage No.</p>
        <p class="details-value"><%= fixture.voyage_number %></p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="details-group">
        <p class="details-label">CP Form</p>
        <p class="details-value"><%= join.nil? ? "" : join.clause.cp_form %></p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class='col-md-3'>
      <div class="details-group">
        <p class="details-label">Vessel Name</p>
        <p class="details-value"><%= fixture.vessel_name %></p>
      </div>
    </div>
    <div class="col-md-3">
      <div class="details-group">
        <p class="details-label">Charterer</p>
        <p class="details-value"><%= fixture.charterer %></p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="details-group">
        <p class="details-label">Contract Type</p>
        <p class="details-value">SPOT</p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <div class="details-group">
        <p class="details-label">Vessel Capacity</p>
        <p class="details-value">35 000 mts</p>
      </div>
    </div>
    <div class="col-md-3">
      <div class="details-group">
        <p class="details-label">Demurrage Rate</p>
        <p class="details-value"><%= number_to_currency(fixture.demurrage_rate, precision: 0, delimiter: ' ', unit: "USD/day", format: "%n %u") %>
        </p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="details-group">
        <p class="details-label">Contract Terms</p>
        <p class="details-value"><%= clause_group.nil? ? "" : clause_group.name %></p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <div class="details-group">
        <p class="details-label">Total Cargo</p>
        <p class="details-value"><%= number_with_delimiter(total_cargo, delimiter: " ").to_s + " mts" %></p>
      </div>
    </div>
    <div class="col-md-3">
      <div class="details-group">
        <p class="details-label">Allowed Laytime</p>
        <p class="details-value"><%= fixture.allowed_laytime.nil? ? "" : fixture.allowed_laytime.to_s + " hours total" %></p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="details-group">
        <p class="details-label">Reversible</p>
        <p class="details-value">Yes</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_flip_modal.html.erb
<div class="modal home-modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">

  <div class="modal-wrap">
    <div class="modal-front is-active">
      <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Sign in</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= simple_form_for(:user, url: session_path(:user)) do |f| %>
              <%= f.input :email, input_html: { autocomplete: 'email' } %>
              <%= f.input :password, input_html: { autocomplete: 'current-password' } %>
              <%= f.input :remember_me, as: :boolean, label: "Remember me", inline_label: true if Devise.mappings[:user] %>
              <%= link_to "Forgot your password?", "#", id: "flip" %>
          </div>
          <div class="modal-footer">
              <%= f.button :button, "Cancel", class: "btn btn-secondary" %>
              <%= f.button :submit, "Sign In", class: "btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="modal-wrap">
      <div class="modal-back">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Forget Your Password?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <%= simple_form_for(:user, url: password_path(:user), method: :post) do |f| %>
              <%= f.error_notification %>

              <%= f.input :reset_password_token, as: :hidden %>
              <%= f.full_error :reset_password_token %>

              <%= f.input :email, input_html: { autocomplete: 'email' } %>

          </div>
          <div class="modal-footer">
              <%= f.button :button, "Go back", class: "btn btn-secondary", id: "flip" %>
              <%= f.button :submit, "Send me reset password instructions", class: "btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- Fixed footer -->
<div class="container-fluid px-6">
<footer class="footer footer-expand-lg footer-light custom-footer">
  <div class="py-3">
    Created by the <a href="#about">Chronos Team</a>.
  </div>
</footer>
</div>

app/views/shared/_hover_button.html.erb
<div class="btn col-md-4 svg-wrapper">
  <svg height="60" width="200" xmlns="http://www.w3.org/2000/svg">
    <rect class="shape" height="60" width="200" />
  </svg>
  <%= link_to "Run Chronos", run_chronos_fixture_events_path, method: :post, class: "btn btn-curious-blue" %>
</div>

app/views/shared/_navbar.html.erb
<!-- Fixed navbar -->
<div class="container-fluid px-6">
<nav class="navbar navbar-expand-lg navbar-light custom-col">
  <%= link_to root_path, class: "logo-url" do %>

    <%= image_tag("hourglass_logo.png", { id: "logo", class: "navbar-brand d-inline align-middle", alt: "Logo", style: "width: 60; height: 60px" } ) %>

    <span class="navbar-brand font-weight-bold logo-col d-inline align-middle" id="navbar-title">CHRONOS</span>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto pl-4">
      <li class="nav-item active pl-5">
        <%= link_to "/fixtures", class: "nav-link" do %>
          Fixtures <span class="sr-only">(current)</span>
        <% end %>
      </li>
      <li class="nav-item pl-5">
        <a class="nav-link cs-link">COA</a>
<!--         For future reference when COA model is created
        <%= link_to "***coa_path***", class: "nav-link" do %>
          COA
        <% end %> -->
      </li>
      <li class="nav-item pl-5">
        <%= link_to('Clauses', clauses_path, class: "nav-link") %>
      </li>
      <li class="nav-item pl-5">
<!--         For future reference when Data model is created
        <%= link_to "***data_path***", class: "nav-link" do %>
          Data
        <% end %> -->
        <a class="nav-link cs-link">Data</a>
      </li>

      <li class="nav-item dropdown pl-5">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Settings
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out dropdown-item"><%= t(".sign_out", default: "Log out") %></i>
          <% end %>
        </div>

        <!-- <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
            <%#= link_to "#" do %>
              <i class="fa fa-cog dropdown-item"> <%= t(".settings", default: "Settings") %></i>
            <%# end %>
            <%#= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out dropdown-item"><%= t(".sign_out", default: "Log out") %></i>
            <%# end %>
         </div> -->
      </li>
    </ul>
  </div>
</nav>
</div>