config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/about' => 'pages#about'
  get '/definitions' => 'pages#definitions'
  get '/presentation' => 'pages#presentation'

  resources :fixtures do
    collection {post :import}
    resources :cargoes, only: [:create, :update]
    resources :events, only: [:index, :new, :create] do
      collection { post :import, :run_chronos }
      end
    end
  resources :clause_groups
  resources :clauses
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :cargo_handlings, dependent: :destroy
  has_many :fixture_cargos, through: :cargo_handlings
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_fixture, only: [:run_chronos, :import, :index, :all_fixture_events]

  def import
    ImportSOFJob.perform_now(params[:file], @fixture)
    if params[:file].nil?
      message = "SOF import failed"
    else
      message = "SOF data imported"
    end
    redirect_to fixture_events_path(@fixture), notice: message
  end

  def run_chronos
    ##TODO: This needs some refactoring, DRY
    all_fixture_events
    reset_events_attributes
    set_allowed_laytime
    group_events

    set_clause_group
    assess_events_clauses

    all_fixture_events
    group_events
    assess_events_laytime

    cumulative_demurrage
    calculate_demurrage
    #only for presentation
    @fixture.required_action = "Invoicing"
    @fixture.save
    #
    redirect_to fixture_events_path(@fixture), notice: "Laytime calculation updated"
  end

  def index
    all_fixture_events
    set_allowed_laytime if @laytime_summary.nil?
    group_events
    @port_events
    cumulative_demurrage
    calculate_demurrage
  end

  private

  def assess_events_clauses
    @port_events.each do |port, terminals|
      terminals.each do |terminal, events|
        @terminal_events = events
        events.each do |event|
          @event = event
          assess_clauses(event, @terminal_events)
        end
      end
    end
  end

  def assess_clauses(event, terminal_events)
    @clause_group.each do |clause|
      clause.bloc_call(event, terminal_events)
    end
  end

  def assess_events_laytime
    @port_events.each do |port, terminals|
      terminals.each do |terminal, events|
        events.each do |event|
          @event = event
          calculate_laytime(event)
        end
      end
    end
  end

  def calculate_laytime(event)
    @start_datetime = event.datetime if event.counting == "Laytime starts"
    @end_datetime = event.datetime if event.counting == "Laytime stops"
    if event.counting == "Laytime stops" && @start_datetime != nil
      @event.laytime = TimeDifference.between(@end_datetime, @start_datetime).in_minutes
      @event.save
    end
  end

  def cumulative_demurrage
    @total_laytime = 0.to_f

    @port_events.each do |port, terminals|
      @port = port
      terminals.each do |terminal, events|
        events.each do |event|
          if event.laytime > 0
            @laytime_summary[@port][:used] += event.laytime
            @total_laytime += event.laytime
          end
        end
      end
    end
    @laytime_summary[:total][:used] = @total_laytime
    time_on_demurrage
  end

  def time_on_demurrage
    @laytime_summary.each do |port, mins|
      if mins[:used] != nil && mins[:allowed] != nil
        on_demurrage = mins[:used] - mins[:allowed]
        @laytime_summary[port][:on_dem] = on_demurrage if on_demurrage > 0
      end
    end
  end

  def calculate_demurrage
    if @laytime_summary[:total][:on_dem] != nil
      @fixture.total_demurrage = (@laytime_summary[:total][:on_dem] * ( @fixture.demurrage_rate / 1440 )).round(2)
      @fixture.save
    end
  end

  ## setting up

  def set_allowed_laytime
    @laytime_summary = Hash.new
    @cargoes.each do |cargo|
      @laytime_summary[cargo.load_port] = {used: 0.to_f}
      @laytime_summary[cargo.disch_port] = {used: 0.to_f}
    end
    @laytime_summary[:total] = {allowed: @fixture.allowed_laytime.to_f * 60}
  end

  def all_fixture_events
    @handlings = Set.new
    @events_set = Set.new
    @cargoes = FixtureCargo.where(fixture: @fixture)

    @cargoes.each do |cargo|
      cargo.cargo_handlings.each { |handling| @handlings << handling }
    end

    @handlings.each { |handling| @events_set << handling.event } if @handlings.length > 0
    @events = order_by_time(@events_set.to_a)
  end

  def reset_events_attributes
    destroyables = []
    @events.each do |event|
      destroyables << event if event.dummy == true
      event.counting = ""
      event.laytime = 0.to_f
      event.save
    end
    @events.reject! { |event| event.dummy == true }
    destroyables.each { |dummy_event| dummy_event.destroy! }
  end

  def group_events
    @port_events = @events.group_by(&:port).transform_values do |events|
      events.group_by(&:terminal)
    end
  end

  def order_by_time(events_array)
    events_array.sort_by! {|event| event.datetime }
  end

  def set_clause_group
    @clause_group = @fixture.clause_group.clauses
  end

  def set_fixture
    @fixture = Fixture.find(params[:fixture_id])
  end
end

app/views/events/_event_row.html.erb
<% @obls = [] %>
<% event.cargo_handlings.each do |handling| %>
  <% @obls << handling.fixture_cargo.obl %>
<% end %>

<tr>
  <!-- title -->
  <td class="align-middle"><%= event.title %></td>
  <!-- obl -->
  <td class="align-middle"><%= @obls.join('') if @obls.length == 1 %></td>
  <!-- date -->
  <td class="align-middle"><%= event.datetime.day %> / <%= event.datetime.month %></td>
  <!-- time -->
  <td class="align-middle"><%= event.datetime.to_time.strftime "%H:%M" %></td>
  <!-- counting -->
  <td class="align-middle"><%= event.counting %></td>
  <!-- Laytime -->
  <td class="align-middle">
    <% if event.laytime > 0.to_f %>
      <%= event.laytime.to_i / 60 %>:<%= event.laytime.to_i % 60 %>
    <% end %>
  </td>
  <!-- optional -->
  <td class="align-middle">  </td>
  <!-- optional -->
  <td class="align-middle"> .. </td>
</tr>

app/views/events/_events_fixture_fields.html.erb
<div class="row">
  <div class='col-md-2'>
    <%= f.input :reference_no, as: :fake,
                label: "Reference No.",
                placeholder: @fixture.reference_no %>
  </div>
  <div class="col-md-2">
    <%= f.input :voyage_number, as: :fake,
                label: "Voyage No.",
                placeholder: @fixture.voyage_number.to_s %>
  </div>

    <% @clause_group = @fixture.clause_group %>
    <% @join = ClauseGroupJoin.where(clause_group: @clause_group).first %>
    <% @cp_form = @join.clause.cp_form %>

  <div class="col-md-3">
    <%= f.input :clause_group, as: :fake,
                label: "CP Form",
                placeholder: @cp_form %>
  </div>
</div>

<div class="row">
  <div class='col-md-2'>
    <%= f.input :vessel_name, as: :fake,
                label: "Vessel Name",
                placeholder: @fixture.vessel_name %>
  </div>
  <div class="col-md-2">
    <%= f.input :charterer, as: :fake,
                label: "Charterer",
                placeholder: @fixture.charterer %>
  </div>

  <div class="col-md-3">
    <%= f.input :contract_type, as: :fake,
                label: "Contract Type",
                placeholder: "SPOT"%>
  </div>
  <div class="col-md-4 mt-3">
    <%= link_to run_chronos_fixture_events_path, method: :post, class: "btn", id: "hover-btn" do %>
      <div class="svg-wrapper">
        <svg height="60" width="320" xmlns="http://www.w3.org/2000/svg">
          <rect class="shape-chronos" height="60" width="320" />
          <div class="hover-text">RUN CHRONOS</div>
        </svg>
      </div>
    <% end %>
  </div>

</div>

<div class="row">
  <div class="col-md-2">
    <%= f.input :vessel_dwt, as: :fake,
                label: "Vessel Capacity",
                placeholder: "35 000 mts" %>
  </div>

  <div class="col-md-2">
    <%= f.input :demurrage_rate, as: :fake,
                label: "Demurrage Rate",
                placeholder: number_to_currency(@fixture.demurrage_rate, precision: 0, delimiter: ' ', unit: "USD/day", format: "%n %u") %>
  </div>

  <div class="col-md-3">
    <%= f.input :contract_terms, as: :fake,
                label: "Contract Terms",
                placeholder: @clause_group.name %>
  </div>
</div>

<% @total_cargo = 0 %>
<% FixtureCargo.where(fixture: @fixture).each {|cargo| @total_cargo += cargo.quantity_mts } %>

<div class="row">
  <div class="col-md-2">
    <%= f.input :total_cargo_qty, as: :fake,
                label: "Total Cargo",
                placeholder: @total_cargo.to_s + " mts" %>
  </div>
  <div class="col-md-2">
    <%= f.input :allowed_laytime, as: :fake,
                label: "Allowed Laytime",
                placeholder: @fixture.allowed_laytime.to_s + " hours total" %>
  </div>
  <div class="col-md-3">
    <%= f.input :reversable, as: :fake,
                label: "Reversible",
                placeholder: "yes" %>
  </div>
</div>

app/views/events/_events_table.html.erb
<div class="port-events">
 <table class="table table-sm table-striped table-hover">
  <h2 class="pt-2"><%= port %></h2>
    <% terminals.each do |terminal, events| %>
      <h4 class="mt-2"><%= terminal %></h4>
      <%= render "events_table_body", events: events %>
    <% end %>
  </table>
</div>

app/views/events/_events_table_body.html.erb
<thead>
  <tr>
    <th style="width: 18%">Title</th>
    <th style="width: 4%" class="obl">Obl</th>
    <th style="width: 6%">Date</th>
    <th style="width: 8%">Time</th>
    <th style="width: 12%">Counting</th>
    <th style="width: 5%">Laytime</th>
    <th style="width: 25%">Comments</th>
    <th style="width: 10%"></th>
  </tr>
</thead>
<tbody>
  <% events.each do |event| %>
    <%= render "event_row", event: event %>
  <% end %>
</tbody>

app/views/events/_summary_row.html.erb
<tr>
  <!-- Port -->
  <td class="align-middle"><%= port %></td>
  <!-- Laytime Used -->
  <td class="align-middle">
    <% if mins[:used].nil? %>
      <%= "" %>
    <% elsif mins[:used] == 0.0 %>
      <%= "-" %>
    <% else %>
      <%= "#{mins[:used].to_i / 60 }hrs:#{mins[:used].to_i % 60}min" %>
    <% end %>
  </td>
  <!-- Laytime Allowed -->
  <td class="align-middle">
    <% if mins[:allowed].nil? %>
      <%= "" %>
    <% elsif mins[:allowed] == 0.0 %>
      <%= "-" %>
    <% else %>
      <%= "#{mins[:allowed].to_i / 60 }hrs:#{mins[:allowed].to_i % 60}min" %>
    <% end %>
  </td>
  <!-- Hours on Demurrage -->
  <td class="align-middle">
    <% if mins[:on_dem].nil? %>
      <%= "" %>
    <% elsif mins[:on_dem] == 0.0 %>
      <%= "-" %>
    <% else %>
      <%= "#{mins[:on_dem].to_i / 60 }hrs:#{mins[:on_dem].to_i % 60}min" %>
    <% end %>
  </td>
</tr>

app/views/events/index.html.erb
<div class="container-fluid px-6 pb-3">

  <div class="events__voyage-details">
    <h2 class="mb-2">
      <%= link_to fixture_path(@fixture) do %>
        <i class='fas fa-chevron-left'></i>
      <% end %>&nbsp;&nbsp;
      Demurrage Report
    </h2>

    <div class="fixture-details">
      <div class="fixture-details-container">
        <%= render 'shared/fixture_details', fixture: @fixture %>
      </div>
      <div class="fixture-buttons-container">
        <%= link_to run_chronos_fixture_events_path, method: :post, class: "btn hover-btn", id: "chronos-btn" do %>
          <div class="svg-wrapper">
            <svg height="60" width="320" xmlns="http://www.w3.org/2000/svg">
              <rect class="shape-chronos" height="60" width="320" />
              <div class="hover-text">RUN CHRONOS</div>
            </svg>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="events__events-table">
    <h2 class="mb-3 pb-3">Port Events</h2>

    <div class="import-file mb-4">
      <%= form_tag import_fixture_events_path, multipart: true do %>
        <span class="outset">
          <%= file_field_tag :file %>
          <%= submit_tag 'Upload SOF', class: "btn btn-curious-blue" %>
      <% end %>
        </span>
    </div>


    <% unless @port_events.nil? %>
        <% @port_events.each do |port, terminals| %>
          <%= render "events_table", port: port, terminals: terminals %>
        <% end %>
    <% end %>
  </div>

  <div class="events__demurrage-summary">
    <h2 class="">Summary</h2>

    <div class="row">
      <div class="col-md-8">
        <div class="summary-table">
          <table class="table table-sm table-striped">
            <thead>
              <tr>
                <th>Port</th>
                <th>Laytime Used</th>
                <th>Laytime Allowed</th>
                <th>Hours on Demurrage</th>
              </tr>
            </thead>
            <tbody>
              <% @laytime_summary.each do |port, mins| %>
                <%= render "summary_row", port: port, mins: mins %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <div class="demurrage-sum">
          <div class="demurrage-rate mt-1">
            <h5>Demurrage Rate</h5>
            <h5 class="double-underline"><%= number_to_currency(@fixture.demurrage_rate, precision: 0, delimiter: ' ', unit: "USD pdpr", format: "$%n %u") %></h5>
          </div>
          <div class="demurrage-rate mt-3">
            <h4>Invoice Amount</h4>
            <h4><%= number_to_currency(@fixture.total_demurrage, precision: 2, delimiter: ' ', unit: "USD", format: "$%n %u") %>
            </h4>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>