config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/about' => 'pages#about'
  get '/definitions' => 'pages#definitions'
  get '/presentation' => 'pages#presentation'

  resources :fixtures do
    collection {post :import}
    resources :cargoes, only: [:create, :update]
    resources :events, only: [:index, :new, :create] do
      collection { post :import, :run_chronos }
      end
    end
  resources :clause_groups
  resources :clauses
end

app/views/pages/about.html.erb
<div class="container-fluid px-6">
  <div class="card">
    <h2>Chronos Team</h2>
    <h3>Le Wagon Batch #204 - Rio de Janeiro</h3>

  </div>


    <div class="d-flex justify-content-center">
      <div class="member-card">
        <div class="foto-wrap" id="CEO">
        </div>
        <div class="member-name">
          <p>Richard Van Den Broek</p>
        </div>
      </div>
    </div>


    <div class="d-flex justify-content-around">
      <div class="member-card">
        <div class="foto-wrap" id="Steven">
        </div>
        <div class="member-name">
          <p>Steven Bowen</p>
        </div>
      </div>
      <div class="member-card">
        <div class="foto-wrap" id="Justin">
        </div>
        <div class="member-name">
          <p>Justin Holt</p>
        </div>
      </div>
      <div class="member-card">
        <div class="foto-wrap" id="Manuel">
        </div>
        <div class="member-name">
          <p>Manuel Winzler</p>
        </div>
      </div>
    </div>


  </div>

app/views/pages/definitions.html.erb
<div class="definitions">

  <div class="mt-3 pb-3">
    <h2 class="definitions__word">
      Laytime
    </h2>

    <blockquote class="definitions__quotes">
    <h3 class="definitions__text old-def">
      The period of time allowed by a shipowner to a carrier to carry out cargo loading or discharging operations.
    </h3>
    <h3 class="definitions__text new-def pt-2" style="display: none">
      THE (AGREED UPON) AMOUNT OF TIME IT TAKES TO LOAD AND UNLOAD CARGO.
    </h3>
    </blockquote>
  </div>

  <div class="mt-4">
    <h2 class="definitions__word">
      Demurrage
    </h2>
    <blockquote class="definitions__quotes">
    <h3 class="definitions__text old-def">
      The compensation payable to a carrier of freight whose vehicle or vessel is
      delayed, as by failure to load or unload the freight within the time allowed.
    </h3>
    <h3 class="definitions__text new-def pt-2" style="display: none">
      LATE FEE!!!
    </h3>
  </div>

</div>

app/views/pages/home.html.erb
<div class="home-container">
  <div class="position-absolute mt-2 mr-3 hamburger">

    <!-- Button trigger modal
    <button type="button" class="btn btn-primary position-absolute mt-2 mr-3 hamburger" data-toggle="modal" data-target="#exampleModalCenter">
      <i class="fa fa-bars fa-1x"></i>
    </button>
  </div>

    Sign in modal
      <%= render partial: "shared/flip_modal" %> -->

    <!-- Button trigger modal  ORIGINAL -->
    <button class="btn btn-default banner-btn" type="button" data-toggle="modal" data-target="#exampleModalCenter">
      <i class="fa fa-bars fa-2x"></i>
    </button>
  </div>

    <!-- Sign in modal ORIGINAL -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content home-modal">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Sign in</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= simple_form_for(:user, url: session_path(:user)) do |f| %>
              <%= f.input :email, input_html: { autocomplete: 'email' } %>
              <%= f.input :password, input_html: { autocomplete: 'current-password' } %>
              <%= f.input :remember_me, as: :boolean, label: "Remember me", inline_label: true if Devise.mappings[:user] %>
              <%= link_to "Forgot your password?", "#", id: "flip1" %>
          </div>
          <div class="modal-footer">
              <%= f.button :button, "Cancel", class: "btn btn-secondary" %>
              <%= f.button :submit, "Sign In", class: "btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>


  <div class="banner">
    <div class="banner-content">
      <%= image_tag("hourglass.jpeg", class: "banner-watermark") %>
      <h1>CHRONOS</h1>
      <p>Fully automated laytime management system</p>
      <%= link_to definitions_path do %>
        <%= render "shared/blob_button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/presentation.html.erb
<div class="home-container">

  <div class="banner">
    <div class="banner-content">
      <%= image_tag("hourglass.jpeg", class: "banner-watermark") %>
      <h1>CHRONOS</h1>
      <p>Fully automated laytime management system</p>
      <%= link_to definitions_path do %>
        <%= render "shared/blob_button" %>
      <% end %>
    </div>
  </div>
</div>